apiVersion: v1
kind: Service
metadata:
  name: queuebernetes-simple-service
  labels:
    app: queuebernetes-simple
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: queuebernetes-simple
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuebernetes-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queuebernetes-simple
  template:
    metadata:
      labels:
        app: queuebernetes-simple
    spec:
      containers:
      - name: queuebernetes-simple
        image: 'us.gcr.io/GCLOUD_PROJECT/queuebernetes-examples:latest'
        imagePullPolicy: Always
        command: ["node"]
        args: ["/app/simple/worker.js"]
        # defines the health checking
        livenessProbe:
          # an http probe
          httpGet:
            path: /healthz
            port: 3000
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          # an http probe
          httpGet:
            path: /healthz
            port: 3000
          # length of time to wait for a pod to initialize
          # after pod startup, before accepting requests
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 0.01
            memory: 32Mi
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB
          value: mongodb://testUser:test@mongod-0.mongodb-service.test.svc.cluster.local:27017/testQueue?authMechanism=DEFAULT&authSource=admin
        - name: DEBUG
          value: express:*
