apiVersion: v1
kind: Service
metadata:
  name: queuebernetes-controller-service
  labels:
    app: queuebernetes-controller
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: queuebernetes-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuebernetes-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queuebernetes-controller
  template:
    metadata:
      labels:
        app: queuebernetes-controller
      annotations:
        queuebernetes.io/minReplicas: "0"
        queuebernetes.io/maxReplicas: "3"
        queuebernetes.io/maxTasks: "1"
        queuebernetes.io/timeout: "5"
        queuebernetes.io/gracePeriod: "60"
    spec:
      serviceAccountName: queuebernetes-sa
      containers:
      - name: queuebernetes-controller
        image: 'us.gcr.io/GCLOUD_PROJECT/queuebernetes-examples:latest'
        imagePullPolicy: Always
        command: ["node"]
        args: ["/app/examples/controller/controller.js"]
        # defines the health checking
        livenessProbe:
          # an http probe
          httpGet:
            path: /healthz
            port: 3000
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          # an http probe
          httpGet:
            path: /healthz
            port: 3000
          # length of time to wait for a pod to initialize
          # after pod startup, before accepting requests
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 0.01
            memory: 32Mi
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB
          value: mongodb://testUser:test@mongod-0.mongodb-service.test.svc.cluster.local:27017/testQueue?authMechanism=DEFAULT&authSource=admin
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MIN_REPLICAS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['queuebernetes.io/minReplicas']
        - name: MAX_REPLICAS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['queuebernetes.io/maxReplicas']
        - name: MAX_TASKS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['queuebernetes.io/maxTasks']
        - name: TIMEOUT
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['queuebernetes.io/timeout']
        - name: GRACE_PERIOD
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['queuebernetes.io/gracePeriod']
        - name: DEBUG
          value: express:*
