apiVersion: v1
kind: ServiceAccount
metadata:
  name: queuebernetes-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: queuebernetes-role
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: queuebernetes-rb
subjects:
- kind: ServiceAccount
  name: queuebernetes-sa
roleRef:
  kind: Role
  name: queuebernetes-role
  apiGroup: rbac.authorization.k8s.io
