apiVersion: v1
kind: ServiceAccount
metadata:
  name: queuebernetes-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: queuebernetes-cr
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: queuebernetes-rb
subjects:
- kind: ServiceAccount
  name: queuebernetes-sa
  namespace: default
roleRef:
   kind: ClusterRole
   name: queuebernetes-cr
   apiGroup: rbac.authorization.k8s.io
